### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by smanjunath211** [PfisterDaniel/node-red-contrib-whatsapp-cmb#10]
How do i send an image ?

**Comment by elvee77** [comment]
+1
I have the same question here...

**Comment by elvee77** [comment]
Seems like answer can be found here: https://github.com/PfisterDaniel/node-red-contrib-whatsapp-cmb/issues/3
not possible to send images unfortunately...

**Comment by PfisterDaniel** [comment]
@elvee77: thx for your support 👍🏻
