### ISSUE TITLE
I lost my ID

### ISSUE THREAD

**Issue by rsorfei** [PfisterDaniel/node-red-contrib-whatsapp-cmb#11]
Hi!
I mistakenly deleted the message that contained my ID and I'm not able to recover it, I already tried to send the message to get another one, but I wasn't successful.
How can I proceed to recover my ID?

**Comment by PfisterDaniel** [comment]
Please send "Recover APIKey" to the number: +34 644 10 55 84

**Comment by rsorfei** [comment]
Daniel, thank you so much!
It worked now!
