### ISSUE TITLE
callmebot did not reply my text after multiple retries.

### ISSUE THREAD

**Issue by jackkok99** [PfisterDaniel/node-red-contrib-whatsapp-cmb#13]

**Comment by PfisterDaniel** [comment]
Hi,
unfortunately I cannot recreate your problem. Do you have registred your Phonenumber on the Callmebot-Page?
[callmebot.com](https://www.callmebot.com/blog/free-api-whatsapp-messages)

The given title is not very meaningful. 
I need a little more information of the problem, for example: a ScreenShot from your node...

**Comment by Tomschin** [comment]
Had the same problem. I missed the "me" in the registration. After copy and paste "I allow callmebot to send **me** messages" it works fine.
