### ISSUE TITLE
no api key recieved

### ISSUE THREAD

**Issue by ahmedshehtaa** [PfisterDaniel/node-red-contrib-whatsapp-cmb#18]
after send to +34 644 53 78 49 the message I allow callmebot to send me messages from my number +20xxxxxxxx no api key recieved

**Comment by absfilho2** [comment]
The same thing happened to me. I think this solution is no longer working.

**Comment by absfilho2** [comment]
I saw that it was discontinued.

**Comment by PfisterDaniel** [comment]
Please use following PhoneNumber:
+34 644 66 32 62

I have tested it a moment ago and it works perfectly

I have changed the description

**Comment by absfilho2** [comment]
Hi @PfisterDaniel,

Thanks for the feedback.
But I don't know why it didn't work.

![image](https://user-images.githubusercontent.com/57852515/198170225-69583332-1988-4018-a256-b13df115f277.png)

I put the new number and continued to receive no response even after waiting minutes.

![image](https://user-images.githubusercontent.com/57852515/198170332-4468cb0c-ba98-4e12-8cad-238c55b81396.png)

I waited about 10 minutes.

Regards,

Antonio Barbosa.

**Comment by absfilho2** [comment]
I did it again today and it worked! Thanks !
