### ISSUE TITLE
kein empfang am Telefon mehr

### ISSUE THREAD

**Issue by hannoverRed** [PfisterDaniel/node-red-contrib-whatsapp-cmb#2]
Hallo,

ich bekomme in Node Red die Rückmeldung
`Message '' was send successfully`
aber es kommt seit tagen auf dem iPhone nichts mehr an!
lg

**Comment by PfisterDaniel** [comment]
Hallo,

Sorry für die späte Rückmeldung....

Im WhatsApp-Node muss als Message (wenn nicht statisch Str verwendet wird) auch die Ausgabe des vorhergenden Nodes angegeben werden.
![image](https://user-images.githubusercontent.com/9358627/106906520-8ccdf900-66fd-11eb-95f2-9626fb6b6dfc.png)

Das Injection-Node ist wie folgt konfiguriert:
![image](https://user-images.githubusercontent.com/9358627/106906693-b8e97a00-66fd-11eb-86e6-4eb69e1aefa2.png)

Das WhatsApp-Node:
![image](https://user-images.githubusercontent.com/9358627/106906809-d6b6df00-66fd-11eb-9297-c59996e70278.png)
Wichtig hierbei:
![image](https://user-images.githubusercontent.com/9358627/106905955-fc8fb400-66fc-11eb-89a5-41554b732850.png)

Somit sollte das Senden auch funktionieren...

**Comment by PeterAustria** [comment]
Hallo Daniel, guter und einfacher Node!!! Er macht was er soll ohne Schnick-Schnack. Dankeschön!!
Einen kleinen Hinweis hätte ich: Die obige Erklärung, dass der Typ von "Message" auf "msg." geändert werden muss, wenn man einen Text aus einem vorangeschalteten Node übergeben möchte, wäre in der Dokumentation sehr hilfreich. Ich habe einige Zeit gesucht wie das geht :-)
Danke und Liebe Grüße
Peter

**Comment by PfisterDaniel** [comment]
Hallo Peter,
danke für den Hinweis, ist korrigiert. In die Dokumentation wird es im nächsten Release integriert.

Gruß Daniel
