### ISSUE TITLE
Addding Bot to whatsapp Group

### ISSUE THREAD

**Issue by syedlnt** [PfisterDaniel/node-red-contrib-whatsapp-cmb#6]
Hi, i used my number to Whatsapp Bot working fine, While send any message to my number in i recieved message in whatsapp bot, 

Now i need to add this whastapp bot on my group

**Comment by PfisterDaniel** [comment]
Hi, sorry Bit WhatsApp Groups are not supported. I use [Callmebot](https://www.callmebot.com/de/blog/kostenlos-api-whatsapp-nachrichten/) for my Node.

Br Daniel
